apiVersion: v1
data:
  # Airflow / Celery shared secret config variables

  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "bXlzcWw6Ly9yb290OnRvb3JAcmVzdWx0LWJhY2tlbmQ6MzMwNi9haXJmbG93Cg==" # "mysql://root:toor@result-backend:3306/airflow"
  AIRFLOW__CELERY__RESULT_BACKEND: "ZGIrbXlzcWw6Ly9yb290OnRvb3JAcmVzdWx0LWJhY2tlbmQ6MzMwNi9haXJmbG93Cg==" # "db+mysql://root:toor@result-backend:3306/airflow"
  AIRFLOW__CELERY__BROKER_URL: "cmVkaXM6Ly9icm9rZXI6NjM3OS8xCg==" # "redis://broker:6379/1"
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-celery-env
  namespace: airflow
