apiVersion: v1
data:
  GIT_SYNC_BRANCH: branch
  GIT_SYNC_PASSWORD: password
  GIT_SYNC_USERNAME: user
  GIT_SYNC_DEST: dest
  GIT_SYNC_REPO: repo
kind: Secret
metadata:
  creationTimestamp: null
  name: git-sync-secrets
  namespace: airflow
