apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: airflow
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: airflow-logs
#   namespace: airflow
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: airflow
