apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: airflow
  name: airflow
  namespace: airflow
spec:
  ports:
  - name: airflow-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: airflow
  type: LoadBalancer
