apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.31.1
    monitors: airflow
  name: airflow
  namespace: airflow
spec:
  selector:
    matchLabels:
      run: airflow
  namespaceSelector:
    matchNames:
    - airflow
  endpoints: 
  - port: airflow-http
    honorLabels: true
    targetPort: airflow-http
    name: airflow-http
    interval: 5s
    path: /admin/metrics
    basicAuth:
      username:
        key: user
        name: airflow-auth
      password:
        key: password
        name: airflow-auth
