apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.31.1
    app: airflow
    team: frontend
    service-monitor: airflow
  name: prometheus-operator
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: airflow
  namespaceSelector:
    matchNames:
    - airflow
  # endpoints:
  # - honorLabels: true
    # port: http
  endpoints: 
  - port: airflow-http
    honorLabels: true
    interval: 5s
    path: /admin/metrics/
    basicAuth: 
      user:
        key: user
        name: airflow-auth
      password:
        key: password
        name: airflow-auth
