apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.31.1
  name: prometheus-operator
  namespace: airflow
spec:
  clusterIP: None
  ports:
  - name: airflow-http
    port: 8080
    targetPort: airflow-http
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
