apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: celery
  name: celery
  namespace: airflow
spec:
  replicas: 0
  selector:
    matchLabels:
      run: celery
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: celery
    spec:
      containers:
      - image: apache/airflow:master
        name: celery
        resources: {}
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "{AIRFLOW_HOME}/dags"
        - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
          value: "10"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: mysql://root:toor@result-backend:3306/airflow
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: db+mysql://root:toor@result-backend:3306/airflow
        - name: AIRFLOW__CELERY__BROKER_URL
          value: redis://broker:6379/1
        command: ['sh', '-c', 'airflow worker']
        ports:
          - containerPort: 8793
      initContainers:
        - image: mysql:5.7
          name: backend-liveness-check
          command: ['sh', '-c', 'until mysqladmin ping -h $RESULT_BACKEND_ADDRESS -u root --password=toor; do echo Waiting for result backend to start; sleep 1; done;']
          env:
            - name: RESULT_BACKEND_ADDRESS
              value: "result-backend"
status: {}
