apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: celery
  namespace: airflow
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: celery
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: airflow
      metricName: airflow_tasks_per_worker
      averageValue: 2 # Used for a scaling in trigger
      targetValue: 5 # Scale out

  # - type: Pods
  #   pods:
  #     metricName: airflow_dag_status
  #     targetAverageValue: 5
  #     selector:
  #       namespace: airflow
  # - type: Object
  #   object:
  #     target:
  #       kind: Service
  #       name: custom-metrics-apiserver
  #     metricName: airflow_dag_status
  #     targetValue: 1
  # targetCPUUtilizationPercentage: 50
