apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    run: celery
  name: celery
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      run: celery
  serviceName: "celery"
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: celery
    spec:
      containers:
      - image: tomwilkie/git-sync
        name: git-sync
        envFrom:
        - secretRef:
            name: git-sync-secrets
        volumeMounts:
          - name: airflow-dags
            mountPath: /git
      - image: apache/airflow:master
        name: celery
        resources:
          requests:
            cpu: "300m"
            memory: "1024m"
        envFrom:
        - configMapRef:
            name: airflow-env
        command: ['sh', '-c', 'airflow worker']
        ports:
          - name: celery-http
            containerPort: 8793
            protocol: TCP
        volumeMounts:
          - name: airflow-dags
            mountPath: /home/airflow/airflow/dags
            readOnly: false
      initContainers:
        - image: mysql:5.7
          name: backend-liveness-check
          command: ['sh', '-c', 'until mysqladmin ping -h $RESULT_BACKEND_ADDRESS -u root --password=toor; do echo Waiting for result backend to start; sleep 1; done;']
          env:
            - name: RESULT_BACKEND_ADDRESS
              value: "result-backend"
      priorityClassName: celery
      volumes:
        - name: airflow-dags
          emptyDir: {}
