apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: celery
  name: celery
  namespace: airflow
spec:
  ports:
  - name: celery-http
    port: 8793
    protocol: TCP
    targetPort: 8793
  selector:
    run: celery
  type: ClusterIP
