apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: airflow
spec:
  replicas: 2
  enableAdminAPI: true
  logLevel: info
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      monitors: airflow
  serviceMonitorNamespaceSelector:
    matchNames:
    - airflow
  # alerting:
  #   alertmanagers:
  #   - namespace: airflow
  #     name: alertmanager
  #     port: web
