apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: airflow
spec:
  replicas: 2
  enableAdminAPI: true
  logLevel: info
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: service-monitor
  resources:
    requests:
      cpu: 0.15
      memory: "500Mi"
    limits:
      cpu: 1
      memory: "2000Mi"
  # matchLabels:
  # monitors: airflow
  serviceMonitorNamespaceSelector:
    matchNames:
      - airflow
      - cadvisor
  # alerting:
  #   alertmanagers:
  #   - namespace: airflow
  #     name: alertmanager
  #     port: web
