apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    prometheus: prometheus
  namespace: airflow
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    protocol: TCP
    # targetPort: web
  selector:
    prometheus: prometheus
    # namespace: airflow
  # namespaceSelector:
  #   matchNames:s
  #   - airflow
