apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    prometheus: prometheus
  namespace: airflow
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    protocol: TCP
  selector:
    prometheus: prometheus
