apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: airflow
spec:
  type: LoadBalancer
  ports:
  - name: prometheus-http
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
