apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadvisor
commonLabels:
  app: cadvisor
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- ds.yaml
- ns.yaml
- podsecuritypolicy.yaml
- sa.yaml
- svc.yaml
- pc.yaml
