apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: flower
  name: flower
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flower
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flower
    spec:
      priorityClassName: flower
      containers:
      - image: apache/airflow:master
        name: flower
        ports:
          - containerPort: 5555
            name: flower-http
        livenessProbe:
          httpGet:
            path: /api/workers
            port: flower-http
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          requests:
            cpu: 0.1
            memory: "100Mi"
          limits:
            cpu: 0.5
            memory: "1024Mi"
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "{AIRFLOW_HOME}/dags"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "mysql://root:toor@result-backend:3306/airflow"
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: db+mysql://root:toor@result-backend:3306/airflow
        - name: AIRFLOW__CELERY__BROKER_URL
          value: redis://broker:6379/1
        command: ["sh", "-c", "unset FLOWER_PORT && airflow flower"]
        # ValueError: invalid literal for int() with base 10: 'tcp://10.12.7.84:5555'
      initContainers:
        - image: mysql:5.7
          name: backend-liveness-check
          command: ['sh', '-c', 'until mysqladmin ping -h $RESULT_BACKEND_ADDRESS -u root --password=toor; do echo Waiting for result backend to start; sleep 1; done;']
          env:
            - name: RESULT_BACKEND_ADDRESS
              value: "result-backend"
status: {}
