apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
spec:
  ports:
  - name: grafana-http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: grafana
  type: LoadBalancer
