apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        resources: {}
        ports:
          - containerPort: 3306
        args:
          - "--explicit-defaults-for-timestamp=1"
        env:
        - name: MYSQL_DATABASE
          value: airflow
        - name: MYSQL_ROOT_PASSWORD
          value: toor
        - name: MYSQL_USERNAME
          value: user
        - name: MYSQL_PASSWORD
          value: password
status: {}
