apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
  namespace: airflow
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
  type: ClusterIP
status:
  loadBalancer: {}
