apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result-backend
  name: result-backend
  namespace: airflow
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  type: ClusterIP
status:
  loadBalancer: {}
