apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: airflow
  namespace: airflow
  labels:
    provisioner: gce
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
allowVolumeExpansion: true
